# CAIXAVERSO - FC2 | Analista Dados - I
## Curso Análise Exploratória de Dados
### Aluno: Renato Tomio Yodono

In [ ]:
# importando bibliotecas
import pandas as pd
import matplotlib as plt
import seaborn as sns
import numpy as np

In [ ]:
# lendo e conhecendo o dataset
df = pd.read_csv('vendas_supermercado_com_cliente.csv')

In [6]:
df.head(1)

,Data,Produto,Categoria,Preço,Quantidade,Desconto,Total_Venda,Idade,Renda
0,2023-01-01,Maçãs,Alimentos Frescos,16.46,10,0.0,164.6,49,2715.61

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20075 entries, 0 to 20074
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Data         20075 non-null  str
 1   Produto      20075 non-null  str
 2   Categoria    20075 non-null  str
 3   Preço        20075 non-null  float64
 4   Quantidade   20075 non-null  int64
 5   Desconto     20075 non-null  float64
 6   Total_Venda  20075 non-null  float64
 7   Idade        20075 non-null  int64
 8   Renda        20075 non-null  float64
dtypes: float64(4), int64(2), str(3)
memory usage: 1.4 MB

In [ ]:
df.describe()

In [9]:
df['Data'] = pd.to_datetime(df['Data'])

### 1. Quais  foram   as  categorias de  produtos  mais  vendidos  e  em   quais  meses  eles  tiveram   o maior pico de vendas?

In [12]:
# vendas por categoria
df.groupby('Categoria', as_index=False)[['Quantidade']].sum().sort_values(by='Quantidade', ascending=False)

                     Categoria  Quantidade
0            Alimentos Frescos       54755
7        Produtos de Mercearia       21857
3            Laticínios e Ovos       18602
6          Produtos de Limpeza       18448
5  Produtos de Higiene Pessoal       18374
1                      Bebidas       18206
4                     Pet Shop       18081
2                   Congelados       18051
8        Utilidades Domésticas       14530

In [ ]:
# vendas por mês
df.groupby(['Categoria','Data'])['Quantidade'].sum()

AttributeError: 'str' object has no attribute 'dt'

### 2. Qual a média de vendas diárias por categoria de produto?

### 3. Quais   produtos   apresentam   a   maior   sazonalidade   nas   vendas   (ex.:   frutas   e   vegetais, sorvetes)?

### 4. Quais as faixas etárias contribuíram mais para as vendas totais? Para responder essa pergunta, crie uma coluna com a faixa etária, considerando: entre 18 e 35 (jovem), entre 36 e 59 (adulto) e acima de 60 anos (idoso).

### 5. Qual é a relação entre a idade dos clientes e a categoria de produto mais vendida para cada?

### 6. Qual a distribuição das vendas ao longo dos dias da semana?

### 7. Como as vendas mensais se comparam antes e durante a Black Friday?

### 8. Qual é o ticket médio (valor médio das vendas) por faixa etária e como ele varia entre diferentes categorias de produto?

### 9. Comparando a semana da “Black Friday” com a do Natal, qual semana a empresa teve melhores desempenhos em relação à média de vendas?

### 10. Qual foi o impacto das promoções (descontos aplicados) nas vendas? Quais produtos tiveram o maior aumento nas vendas durante as promoções?